from src.lfrenderer.scene.custom.chessboard import ChessboardSceneManager
from src.lfrenderer.scene.custom.chessboard_silvr import ChessboardSceneSilvrManager
from src.lfrenderer.scene.custom.objaverse import ObjaverseSceneManager